version: '3'
services:
  app:
    build: .
    stdin_open: true
    tty: true
    env_file:
      ./.env
    ports:
      - "5000:5000"
    depends_on:
      - db
      - cache
    volumes:
      - ./:/app
  db:
    image: postgres
    env_file:
      ./.env
    ports:
      - "5432:5432"
  adminer:
    image: adminer
    ports:
      - "8080:8080"
  cache:
    image: 'redis'
    ports:
      - "6379:6379"

