version: "3"

networks:
  gello-network:
services:
  app:
    build: .
    stdin_open: true
    tty: true
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./:/app
    networks:
      - gello-network

  db:
    image: postgres
    ports:
      - "5432:5432"
    networks:
      - gello-network
    environment:
      POSTGRES_DB: "${POSTGRES_DB:-gello}"
      POSTGRES_USER: "${POSTGRES_USER:-user}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-password}"

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 20s
      timeout: 30s
      retries: 3
      start_period: 30s

    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  adminer:
    image: adminer
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    networks:
      - gello-network

  cache:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - gello-network
